default: help

new:
	node build/bin/new.js $(filter-out $@,$(MAKECMDGOALS))

help:
	@echo "\033[36m make new <component-type(css/form/js)> <component-name> Make a new component  ---demo :make new css button \033[0m"