/* Automatically generated by './build/bin/new.js' */
import Button from '../packages/button/index.js'
import Header from '../packages/header/index.js'
import Tabbar from '../packages/tabbar/index.js'
import TabItem from '../packages/tab-item/index.js'
import TabContainer from '../packages/tab-container/index.js'
import TabContainerItem from '../packages/tab-container-item/index.js'
import Navbar from '../packages/navbar/index.js'

const components = [
  Button,
  Header,
  Tabbar,
  TabItem,
  TabContainer,
  TabContainerItem,
  Navbar
]

// 提供plugins的install方法
const install = function (Vue, opt = {}) {
  // if (install.installed) return
  components.map(component => {
    Vue.component(component.name, component)
  })
}

if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue)
}

// install()

module.exports = {
  install,
  ...components
}

module.exports.default = module.exports
